### ISSUE TITLE
Django 1.8.3 support

### ISSUE THREAD

**Issue by psilar** [doconix/django-mako-plus#11]
Is Django 1.8 supported by this app.  I'm trying to use the contrib messages app but no messages are appearing on pages.  This appears to be because, although they are stored in a cookie, the context processors never get run to provide them as local variables.  Is there some voodoo needed because of the changes to the Django template backend?

**Comment by doconix** [comment]
It is 1.8 compatible.  1.8 is what I’m using to test it.

However, it doesn’t use the 1.8 “new” template framework.  A couple months ago, I switched over to the “standard” template methods that 1.8 now provides and put DMP as a template processor, but it didn’t work because we need different API calls than the standard ones.  I finally gave up on the idea because it was a hack job to make it work together.  The biggest problem is the standard template framework that Django provides isn’t app-aware.  DMP processes templates within the context of the app they are in.  Django doesn’t do it that way.  To integrate fully into the new standard framework, we’d have to be able to tell what app a template lives in.  If we could get this without hack work, I could integrate it fully into the new Django template framework.

To bring the above to your question, since DMP isn’t using the new template framework that 1.8 provides, it might not be processing things like context processors.  I’ve never used them so I haven’t built them into the framework.

I have no problem bringing them into DMP, though.  I just need the time to figure out what needs to be done.

-- 
Conan C. Albrecht, Ph.D.
Information Systems Department
Brigham Young University
ca@byu.edu
KG7USZ
http://goalbrecht.com/
