### ISSUE TITLE
"dmp_startapp" changed to just "startapp"

### ISSUE THREAD

**Issue by Spievat** [doconix/django-mako-plus#18]
[This](https://github.com/doconix/django-mako-plus#create-a-dmp-style-app) part of the installation guide mentions to use 

`python3 manage.py dmp_startapp homepage`

But should it be this?

`python3 manage.py startapp homepage`

I get this error:

```
C:\Users\spiva\Desktop\IS 413 Final\Test>python manage.py dmp_startapp homepage
Unknown command: 'dmp_startapp'
Type 'manage.py help' for usage.
```

**Comment by doconix** [comment]
It should be dmp_startapp.  DMP has a different structure than normal Django apps, so I had to make a different start app command.  

I think the reason you're getting the error is because DMP isn't in your INSTALLED_APPS.  Check that you did steps #1 and #2 from the installation guide. If it's there, the dmp_startapp command should work.  You can also run just

python3 manage.py

Without a command to see what commands are available. You should see a section for [django_mako_plus].

**Comment by Spievat** [comment]
Yep, that was it! 

I had to add DMP to the installed_apps, delete my homepage app and remove it from installed_apps, and then run dmp_startapp again. 

Thank you!

![image](https://cloud.githubusercontent.com/assets/13740128/14682320/48d28822-06e2-11e6-859d-7e7006081653.png)
