### ISSUE TITLE
Is there a way to use DMP without the dmp router?

### ISSUE THREAD

**Issue by knowsuchagency** [doconix/django-mako-plus#21]
This package is amazing but I was wondering if there was a way to use it without following dmp routing and view conventions. 

I have a django app already, and I would simply like to replace the syntax of my current django templates with what dmp provides with mako. Is there a straightforward way of doing so?

**Comment by doconix** [comment]
Hello from the Rocky Mountains, @knowsuchagency!  Just an aside before I answer your question--I live in Utah, where the primary data center for the NSA is.  So I'm smiling at your username.  If a nuclear war comes, my state will be the first to go up in the flash.  You may not want to rely on DMP because it will be long gone if that happens.  Ha ha.

Yes, there is a straightforward way of using DMP without all the extras.  I took some time this morning and updated the documentation to describe what you are after.  Check out https://github.com/doconix/django-mako-plus#rendering-mako-without-dmp-routing.  

The first part shows creating a project, which you've already got.  Then it shows the minimal modifications necessary to render a Mako template with DMP.  Let me know what questions you have about it.

Also, be sure to upgrade your DMP.  I fixed a small bug that can occur when DMP is used without the router. `pip3 install --upgrade django-mako-plus`

**Comment by knowsuchagency** [comment]
Haha let's hope that doesn't happen but in the event that it does, I'll be sure to keep in mind that it would need a maintainer! Thanks for the quick reply and the update to the documentation @doconix. 

I have to say, I wish more projects were as thoroughly documented as yours --even in the docstrings. It makes everything much easier to use and understand.

The one suggestion I would make is to let users know to specify a default application when using DMP with an existing Django project, whatever that may be. I made sure to update DMP with pip before trying it with my existing application and it worked like a charm so long as I specified the **DEFAULT PAGE** and **DEFAULT_APP** attributes in the DMP entry in settings.TEMPLATES.

Thanks again!
